### ISSUE TITLE
mrfy-bench should record and emit the GHC version used

### ISSUE THREAD

**Issue by nrnrnr** [ndaniels/MRFy#4]
This might be done already, but I haven't run `mrfy-bench` because the instructions are buried where I can't easily find them....

**Comment by BurntSushi** [comment]
[Instructions have been committed to `BENCH`.](https://github.com/ndaniels/MRFy/blob/master/BENCH)

**Comment by BurntSushi** [comment]
Done in https://github.com/ndaniels/mrfy-bench/commit/188547c9c5645408f5a21b052e127b14b2172106.
