### ISSUE TITLE
Add valgrind support to mrfy-bench

### ISSUE THREAD

**Issue by nrnrnr** [ndaniels/MRFy#5]
I'd like to have a meaningful viterbi benchmark that's short enough to use valgrind's profiler.  That will give us some information about instruction counts and instruction mix.  And the numbers should be comparable across platforms.

**Comment by BurntSushi** [comment]
Done in https://github.com/ndaniels/mrfy-bench/commit/27c31d2ac671d33705a0a9a72a3f54bc925378a7.

**Comment by BurntSushi** [comment]
e.g.

``` bash
./viterbi-bench -valgrind -b master -- --leak-check=full
```
