### ISSUE TITLE
mrfy-bench should record and emit the CPU architecture used

### ISSUE THREAD

**Issue by nrnrnr** [ndaniels/MRFy#6]
We may get different results from x86 and AMD64.

**Comment by BurntSushi** [comment]
I don't think I personally have access to any 32-bit machines.

(Unless I dig out my old P4. I might have a Core Duo laying around somewhere...)

**Comment by ndaniels** [comment]
While I think it's possible that we may have different results between 64-bit AMD and 64-bit Intel processors, I think worrying about legacy 32-bit x86 hardware is ludicrous.

I could dig up a 32-bit PowerPC G4 machine, and an UltraSPARC if need be, but I don't think they're relevant.

(I don't even know if GHC targets those architectures).

**Comment by BurntSushi** [comment]
@ndaniels The reason why this came up is that the new Viterbi is ever-so-slightly faster on my home machine (Sandy Bridge-E), but is about 15% slower on my machine at school (Ivy Bridge) **and** on my AMD machine (K10). So it might make sense to look at other architectures...

**Comment by nrnrnr** [comment]
My 32-bit machines are extremely relevant, thank you very much. I believe Don Knuth had something trenchant to say on this topic.

**Comment by BurntSushi** [comment]
Found it:

> A Flame About 64-bit Pointers
> 
> It is absolutely idiotic to have 64-bit pointers when I compile a program that uses less than 4 gigabytes of RAM. When such pointer values appear inside a struct, they not only waste half the memory, they effectively throw away half of the cache.
> 
> The gcc manpage advertises an option "-mlong32" that sounds like what I want. Namely, I think it would compile code for my x86-64 architecture, taking advantage of the extra registers etc., but it would also know that my program is going to live inside a 32-bit virtual address space.
> 
> Unfortunately, the -mlong32 option was introduced only for MIPS computers, years ago. Nobody has yet adopted such conventions for today's most popular architecture. Probably that happens because programs compiled with this convention will need to be loaded with a special version of libc.
> 
> Please, somebody, make that possible.

**Comment by BurntSushi** [comment]
Done in https://github.com/ndaniels/mrfy-bench/commit/79216433f946de82571646d03d083013c71ee22c.
